package net.craswell.common.encryption;

/**
 * An encrypted object generated by, or to be processed, by the AesTool.
 * 
 * @author scraswell@gmail.com
 *
 */
public class EncryptedObject {
  /**
   * The initialization vector.
   */
  private byte[] initializationVector;

  /**
   * The salt.
   */
  private byte[] salt;

  /**
   * The cipher text.
   */
  private byte[] ciphertext;

  /**
   * @return The initialization vector.
   */
  public byte[] getInitializationVector() {
    return initializationVector;
  }

  /**
   * Sets the initialization vector.
   * 
   * @param initializationVector The initialization vector bytes.
   */
  public void setInitializationVector(byte[] initializationVector) {
    this.initializationVector = initializationVector;
  }

  /**
   * @return The salt.
   */
  public byte[] getSalt() {
    return salt;
  }

  /**
   * Sets the salt.
   * 
   * @param salt The salt.
   */
  public void setSalt(byte[] salt) {
    this.salt = salt;
  }

  /**
   * @return The cipher text.
   */
  public byte[] getCiphertext() {
    return ciphertext;
  }
  
  /**
   * Sets the cipher text.
   * 
   * @param ciphertext The cipher text.
   */
  public void setCiphertext(byte[] ciphertext) {
    this.ciphertext = ciphertext;
  }
}
